<a href="https://colab.research.google.com/github/AnmolRajpoot25/LLMs_Learnig/blob/main/coding_attention_mechanism_chap3_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 3.3.1 a simple self_attention mechanism without the trainable weights

In [ ]:
import torch

inputs = torch.tensor(
  [[0.43, 0.15, 0.89], # Your     (x^1)
   [0.55, 0.87, 0.66], # journey  (x^2)
   [0.57, 0.85, 0.64], # starts   (x^3)
   [0.22, 0.58, 0.33], # with     (x^4)
   [0.77, 0.25, 0.10], # one      (x^5)
   [0.05, 0.80, 0.55]] # step     (x^6)
)

In [ ]:
input_query = inputs[1]
input_1 = inputs[2]

In [ ]:
torch.dot(input_query, inputs[0])

In [ ]:
i=2
res = torch.dot(inputs[i], input_query)

In [112]:
res

tensor(1.4754)

In [113]:
torch.empty(inputs.shape[0])

tensor([0.0000e+00, 1.6255e-43, 7.7052e+31, 1.9447e+31, 2.1715e-18, 2.3081e-12])

In [114]:
query = inputs[1]
attn_score_2 = torch.empty(inputs.shape[0])
for i , x_i in enumerate(inputs ):
  attn_score_2[i]= torch.dot(x_i, input_query )

In [115]:
attn_score_2

tensor([0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865])

In [116]:
attn_weight_temp = attn_score_2 /attn_score_2.sum()
attn_weight_temp

tensor([0.1455, 0.2278, 0.2249, 0.1285, 0.1077, 0.1656])

In [117]:
attn_weight_temp.sum()

tensor(1.0000)

In [118]:
def softmax_naive(x):
  return torch.exp(x)/torch.exp(x).sum(dim=0)
softmax_naive(attn_score_2)

tensor([0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581])

In [119]:
torch.softmax(attn_score_2, dim=0)

tensor([0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581])

In [120]:
torch.zeros(query.shape)

tensor([0., 0., 0.])

In [121]:
attn_weight_2 = torch.softmax(attn_score_2, dim=0)

print("Attention weights:", attn_weight_2)
print("Sum:", attn_weight_2.sum())

Attention weights: tensor([0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581])
Sum: tensor(1.)


In [122]:
query= inputs[1]
context_vec_2 = torch.zeros(query.shape)
for i , x_i in enumerate(inputs):
  context_vec_2 += attn_weight_2[i]*x_i
print (context_vec_2)

tensor([0.4419, 0.6515, 0.5683])


In [123]:
for i, x_i in enumerate(inputs):
  print(i, inputs[i])


0 tensor([0.4300, 0.1500, 0.8900])
1 tensor([0.5500, 0.8700, 0.6600])
2 tensor([0.5700, 0.8500, 0.6400])
3 tensor([0.2200, 0.5800, 0.3300])
4 tensor([0.7700, 0.2500, 0.1000])
5 tensor([0.0500, 0.8000, 0.5500])


# 3.3.2 Asimple self-attention mechanism without trainable weights

In [124]:
inputs = torch.tensor(
  [[0.43, 0.15, 0.89], # Your     (x^1)
   [0.55, 0.87, 0.66], # journey  (x^2)
   [0.57, 0.85, 0.64], # starts   (x^3)
   [0.22, 0.58, 0.33], # with     (x^4)
   [0.77, 0.25, 0.10], # one      (x^5)
   [0.05, 0.80, 0.55]] # step     (x^6)
)


In [125]:
attn_score = torch.empty(6,6)
for i, x_i in enumerate (inputs):
  for j , x_j in enumerate(inputs):
    attn_score[i,j] = torch.dot(x_i, x_j)
print( attn_score)

tensor([[0.9995, 0.9544, 0.9422, 0.4753, 0.4576, 0.6310],
        [0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865],
        [0.9422, 1.4754, 1.4570, 0.8296, 0.7154, 1.0605],
        [0.4753, 0.8434, 0.8296, 0.4937, 0.3474, 0.6565],
        [0.4576, 0.7070, 0.7154, 0.3474, 0.6654, 0.2935],
        [0.6310, 1.0865, 1.0605, 0.6565, 0.2935, 0.9450]])


In [126]:
attn_score = inputs @ inputs.T # matrix multiplication with its transpose
print(attn_score)

tensor([[0.9995, 0.9544, 0.9422, 0.4753, 0.4576, 0.6310],
        [0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865],
        [0.9422, 1.4754, 1.4570, 0.8296, 0.7154, 1.0605],
        [0.4753, 0.8434, 0.8296, 0.4937, 0.3474, 0.6565],
        [0.4576, 0.7070, 0.7154, 0.3474, 0.6654, 0.2935],
        [0.6310, 1.0865, 1.0605, 0.6565, 0.2935, 0.9450]])


In [127]:
attn_weights = torch.softmax(attn_score, dim =1)
attn_weights

tensor([[0.2098, 0.2006, 0.1981, 0.1242, 0.1220, 0.1452],
        [0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581],
        [0.1390, 0.2369, 0.2326, 0.1242, 0.1108, 0.1565],
        [0.1435, 0.2074, 0.2046, 0.1462, 0.1263, 0.1720],
        [0.1526, 0.1958, 0.1975, 0.1367, 0.1879, 0.1295],
        [0.1385, 0.2184, 0.2128, 0.1420, 0.0988, 0.1896]])

In [128]:
attn_score = inputs @ inputs.T
attn_weights = torch.softmax(attn_score, dim =1)
print(attn_weights)


tensor([[0.2098, 0.2006, 0.1981, 0.1242, 0.1220, 0.1452],
        [0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581],
        [0.1390, 0.2369, 0.2326, 0.1242, 0.1108, 0.1565],
        [0.1435, 0.2074, 0.2046, 0.1462, 0.1263, 0.1720],
        [0.1526, 0.1958, 0.1975, 0.1367, 0.1879, 0.1295],
        [0.1385, 0.2184, 0.2128, 0.1420, 0.0988, 0.1896]])


In [129]:
attn_score = inputs @ inputs.T
attn_weights = torch.softmax(attn_score, dim =1)

all_context_vecs = attn_weights @ inputs

In [130]:
all_context_vecs

tensor([[0.4421, 0.5931, 0.5790],
        [0.4419, 0.6515, 0.5683],
        [0.4431, 0.6496, 0.5671],
        [0.4304, 0.6298, 0.5510],
        [0.4671, 0.5910, 0.5266],
        [0.4177, 0.6503, 0.5645]])

# implementing self- attention  with the the training weights

## computing  the attention weights steps  by step

In [131]:
x_2 = inputs[1]
d_in = inputs.shape[1]
d_out = 2

In [132]:
d_in

3

In [133]:
torch.manual_seed(123)

w_query = torch.nn.Parameter(torch.rand(d_in , d_out))
w_key = torch.nn.Parameter(torch.rand(d_in , d_out))
w_value = torch.nn.Parameter(torch.rand(d_in , d_out))

In [134]:
query_2 = x_2 @w_query
query

tensor([0.5500, 0.8700, 0.6600])

In [135]:
keys = inputs @ w_key
keys


tensor([[0.3669, 0.7646],
        [0.4433, 1.1419],
        [0.4361, 1.1156],
        [0.2408, 0.6706],
        [0.1827, 0.3292],
        [0.3275, 0.9642]], grad_fn=<MmBackward0>)

In [136]:
values = inputs @ w_value
values

tensor([[0.1855, 0.8812],
        [0.3951, 1.0037],
        [0.3879, 0.9831],
        [0.2393, 0.5493],
        [0.1492, 0.3346],
        [0.3221, 0.7863]], grad_fn=<MmBackward0>)

In [137]:
keys_2 = keys[1]
attn_score_22 = torch.dot( query_2 , keys_2 )
attn_score_22

tensor(1.8524, grad_fn=<DotBackward0>)

In [138]:
attn_scores_2  = query_2 @ keys.T
attn_scores_2

tensor([1.2705, 1.8524, 1.8111, 1.0795, 0.5577, 1.5440],
       grad_fn=<SqueezeBackward4>)

In [139]:
d_k = keys.shape[1]
attn_weights_2 = torch.softmax(attn_scores_2/ d_k **0.5  , dim = -1 )
attn_weight_2

tensor([0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581])

In [140]:
attn_weights_2.sum()

tensor(1., grad_fn=<SumBackward0>)

In [141]:
context_vec_2 = attn_weights_2 @ values
context_vec_2

tensor([0.3061, 0.8210], grad_fn=<SqueezeBackward4>)

## implementing a compact self attention class

In [142]:
import torch.nn as nn

class selfAttention_v2( nn.Module):

  def __init__( self , d_in , d_out , qkv_bias = False):
   super(). __init__()
   self.w_query = torch.nn.Linear(d_in , d_out, bias = qkv_bias)
   self.w_key = torch.nn.Linear(d_in , d_out, bias = qkv_bias)
   self.w_value = torch.nn.Linear(d_in , d_out, bias = qkv_bias)

  def forward(self, x):
    query = self.w_query(x)
    keys = self.w_key(x)
    values = self.w_value(x)

    attn_scores = query @ keys.T
    attn_weights= torch.softmax(attn_score/d_k**0.5 , dim = -1 )
    context_vec= attn_weights @ values

    return context_vec



torch.manual_seed(1)
sa_v2 = selfAttention_v2(d_in , d_out)
sa_v2(inputs)

tensor([[-0.0642,  0.0253],
        [-0.0733,  0.0288],
        [-0.0727,  0.0287],
        [-0.0709,  0.0280],
        [-0.0582,  0.0243],
        [-0.0768,  0.0297]], grad_fn=<MmBackward0>)

# Hiding future Words with the casual attention

## Applying a casual attention mask

In [143]:
queries = sa_v2.w_query(inputs)
keys = sa_v2.w_key(inputs)
values = sa_v2.w_value(inputs)

attn_scores = queries @ keys.T
attn_weights = torch.softmax(attn_scores, dim = -1)


In [144]:
context_length = attn_scores.shape[0]
mask_simple  = torch.tril(torch.ones(context_length, context_length))
mask_simple

tensor([[1., 0., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1., 1.]])

In [145]:
masked_simple= attn_weights*mask_simple
masked_simple

tensor([[0.1635, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1698, 0.1642, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1694, 0.1645, 0.1647, 0.0000, 0.0000, 0.0000],
        [0.1700, 0.1641, 0.1644, 0.1663, 0.0000, 0.0000],
        [0.1631, 0.1695, 0.1691, 0.1670, 0.1607, 0.0000],
        [0.1730, 0.1617, 0.1623, 0.1659, 0.1775, 0.1597]],
       grad_fn=<MulBackward0>)

In [146]:
## or  the shortcut methor dto mask the text for the llm model

In [147]:
mask = torch.triu(torch.ones(context_length, context_length), diagonal = 1)
masked = attn_scores.masked_fill(mask.bool(), -torch.inf)
mask
masked

tensor([[ 0.0059,    -inf,    -inf,    -inf,    -inf,    -inf],
        [-0.0103, -0.0435,    -inf,    -inf,    -inf,    -inf],
        [-0.0093, -0.0391, -0.0375,    -inf,    -inf,    -inf],
        [-0.0104, -0.0459, -0.0440, -0.0326,    -inf,    -inf],
        [ 0.0120,  0.0503,  0.0482,  0.0356, -0.0028,    -inf],
        [-0.0205, -0.0885, -0.0848, -0.0628,  0.0052, -0.1008]],
       grad_fn=<MaskedFillBackward0>)

In [148]:
torch.exp(torch.tensor(-99999999))

tensor(0.)

In [149]:
torch.exp(torch.tensor(float("-inf")))

tensor(0.)

In [150]:
attn_weights = torch.softmax( masked/keys.shape[-1]**0.5, dim = -1 )
attn_weights

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5059, 0.4941, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3379, 0.3309, 0.3312, 0.0000, 0.0000, 0.0000],
        [0.2541, 0.2478, 0.2481, 0.2501, 0.0000, 0.0000],
        [0.1976, 0.2031, 0.2028, 0.2010, 0.1956, 0.0000],
        [0.1712, 0.1631, 0.1636, 0.1661, 0.1743, 0.1617]],
       grad_fn=<SoftmaxBackward0>)

## maskinfg  the  addition attention weights with the dropout

In [151]:
torch.manual_seed(123)


layers = torch.nn.Dropout(0.5)

In [152]:
example = torch.ones(6, 6)
example

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [153]:
layers( example)

tensor([[2., 2., 0., 2., 2., 0.],
        [0., 0., 0., 2., 0., 2.],
        [2., 2., 2., 2., 0., 2.],
        [0., 2., 2., 0., 0., 2.],
        [0., 2., 0., 2., 0., 2.],
        [0., 2., 2., 2., 2., 0.]])

In [154]:
dropout_rate = 0.5
1/(1-dropout_rate)

2.0

## Implementing a compact casual self_attention class

In [155]:
batch = torch.stack((inputs ,inputs ),  dim =0)
batch.shape

torch.Size([2, 6, 3])

In [156]:
import torch.nn as nn

class casualAttention( nn.Module):

  def __init__( self , d_in , d_out,context_length  ,dropout , qkv_bias = False):
   super(). __init__()
   self.d_out = d_out
   self.w_query = torch.nn.Linear(d_in , d_out, bias = qkv_bias)
   self.w_key = torch.nn.Linear(d_in , d_out, bias = qkv_bias)
   self.w_value = torch.nn.Linear(d_in , d_out, bias = qkv_bias)
   self.dropout= torch.nn.Dropout(dropout)
   self.register_buffer("mask", torch.triu(torch.ones(context_length, context_length), diagonal = 1))




  def forward(self, x):
    b , num_tokens , d_in = x.shape
    query = self.w_query(x)
    keys = self.w_key(x)
    values = self.w_value(x)

    attn_scores = query @ keys.transpose(1,2)
    attn_scores.masked_fill_(self.mask.bool()[:num_tokens, :num_tokens], -torch.inf)

    attn_weights= torch.softmax(attn_score/keys.shape[-1]**0.5 , dim = -1 )
    attn_weights = self.dropout(attn_weights)
    context_vec= attn_weights @ values

    return context_vec



torch.manual_seed(789)
context_length = batch.shape[1]
dropout = 0.0
ca_v2 = casualAttention(d_in , d_out, context_length , dropout)
context_vecs= ca_v2(batch)
print(context_vecs)
print("\n context_vecs.shape:\n", context_vecs.shape )

tensor([[[-0.0835,  0.0621],
         [-0.0882,  0.0595],
         [-0.0875,  0.0604],
         [-0.0854,  0.0595],
         [-0.0712,  0.0794],
         [-0.0921,  0.0510]],

        [[-0.0835,  0.0621],
         [-0.0882,  0.0595],
         [-0.0875,  0.0604],
         [-0.0854,  0.0595],
         [-0.0712,  0.0794],
         [-0.0921,  0.0510]]], grad_fn=<UnsafeViewBackward0>)

 context_vecs.shape:
 torch.Size([2, 6, 2])


# Extending single _ head  to Multi- head attention

## stacking multiple single-head to multi-head attention

In [165]:
class MultiHeadAttentionWrapper(nn.Module):
  def __init__(self, d_in, d_out , context_length , dropout , num_heads =2 , qkv_bias= False):
    super().__init__()
    self.heads = nn.ModuleList([
        casualAttention(d_in , d_out , context_length , dropout , qkv_bias)
      for _ in range(num_heads)
    ])

  def forward(self, x):
    return torch.cat([head(x) for head in self.heads], dim = -1)

torch.manual_seed(123)


context_length = batch.shape[1]
d_in ,d_out = 3, 2
mha = MultiHeadAttentionWrapper(
    d_in, d_out, context_length, 0.0 , num_heads =2
    )
mha(batch )
context_vecs = mha(batch)
print(context_vecs)
print("\n context_vecs.shape:\n", context_vecs.shape)


tensor([[[-0.5417, -0.0965,  0.5212,  0.3448],
         [-0.5539, -0.1171,  0.5301,  0.3647],
         [-0.5537, -0.1170,  0.5300,  0.3643],
         [-0.5422, -0.1144,  0.5190,  0.3566],
         [-0.5418, -0.1117,  0.5201,  0.3509],
         [-0.5450, -0.1160,  0.5210,  0.3608]],

        [[-0.5417, -0.0965,  0.5212,  0.3448],
         [-0.5539, -0.1171,  0.5301,  0.3647],
         [-0.5537, -0.1170,  0.5300,  0.3643],
         [-0.5422, -0.1144,  0.5190,  0.3566],
         [-0.5418, -0.1117,  0.5201,  0.3509],
         [-0.5450, -0.1160,  0.5210,  0.3608]]], grad_fn=<CatBackward0>)

 context_vecs.shape:
 torch.Size([2, 6, 4])


## implementing multi-head attention with the weight split

In [172]:
class MultiHeadAttention(nn.Module):
    def __init__(self, d_in, d_out, context_length, dropout, num_heads, qkv_bias=False):
        super().__init__()
        assert (d_out % num_heads == 0), \
            "d_out must be divisible by num_heads"

        self.d_out = d_out
        self.num_heads = num_heads
        self.head_dim = d_out // num_heads # Reduce the projection dim to match desired output dim

        self.W_query = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_key = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_value = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.out_proj = nn.Linear(d_out, d_out)  # Linear layer to combine head outputs
        self.dropout = nn.Dropout(dropout)
        self.register_buffer(
            "mask",
            torch.triu(torch.ones(context_length, context_length),
                       diagonal=1)
        )

    def forward(self, x):
        b, num_tokens, d_in = x.shape
        # As in `CausalAttention`, for inputs where `num_tokens` exceeds `context_length`,
        # this will result in errors in the mask creation further below.
        # In practice, this is not a problem since the LLM (chapters 4-7) ensures that inputs
        # do not exceed `context_length` before reaching this forward method.

        keys = self.W_key(x) # Shape: (b, num_tokens, d_out)
        queries = self.W_query(x)
        values = self.W_value(x)

        # We implicitly split the matrix by adding a `num_heads` dimension
        # Unroll last dim: (b, num_tokens, d_out) -> (b, num_tokens, num_heads, head_dim)
        keys = keys.view(b, num_tokens, self.num_heads, self.head_dim)
        values = values.view(b, num_tokens, self.num_heads, self.head_dim)
        queries = queries.view(b, num_tokens, self.num_heads, self.head_dim)

        # Transpose: (b, num_tokens, num_heads, head_dim) -> (b, num_heads, num_tokens, head_dim)
        keys = keys.transpose(1, 2)
        queries = queries.transpose(1, 2)
        values = values.transpose(1, 2)

        # Compute scaled dot-product attention (aka self-attention) with a causal mask
        attn_scores = queries @ keys.transpose(2, 3)  # Dot product for each head

        # Original mask truncated to the number of tokens and converted to boolean
        mask_bool = self.mask.bool()[:num_tokens, :num_tokens]

        # Use the mask to fill attention scores
        attn_scores.masked_fill_(mask_bool, -torch.inf)

        attn_weights = torch.softmax(attn_scores / keys.shape[-1]**0.5, dim=-1)
        attn_weights = self.dropout(attn_weights)

        # Shape: (b, num_tokens, num_heads, head_dim)
        context_vec = (attn_weights @ values).transpose(1, 2)

        # Combine heads, where self.d_out = self.num_heads * self.head_dim
        context_vec = context_vec.contiguous().view(b, num_tokens, self.d_out)
        context_vec = self.out_proj(context_vec) # optional projection

        return context_vec

torch.manual_seed(123)

batch_size, context_length, d_in = batch.shape
d_out = 2
mha = MultiHeadAttention(d_in, d_out, context_length, 0.0, num_heads=2)

context_vecs = mha(batch)

print(context_vecs)
print("context_vecs.shape:", context_vecs.shape)

tensor([[[0.3190, 0.4858],
         [0.2943, 0.3897],
         [0.2856, 0.3593],
         [0.2693, 0.3873],
         [0.2639, 0.3928],
         [0.2575, 0.4028]],

        [[0.3190, 0.4858],
         [0.2943, 0.3897],
         [0.2856, 0.3593],
         [0.2693, 0.3873],
         [0.2639, 0.3928],
         [0.2575, 0.4028]]], grad_fn=<ViewBackward0>)
context_vecs.shape: torch.Size([2, 6, 2])
